# This file is part of REANA.
# Copyright (C) 2017, 2018 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - "3.6"

services:
  - docker

before_script:
- curl https://raw.githubusercontent.com/stoplightio/prism/master/install.sh | sudo sh
- prism run --mock --list --spec /home/travis/build/dinosk/reana-server/reana_server/openapi_connections/reana_workflow_controller.json &

before_install:
  - pip install -r requirements-dev.txt
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls

install:
  - travis_retry pip install -e .[all]

script:
  - ./run-tests.sh

after_success:
  - coveralls
